# Generated by Django 4.0.5 on 2022-06-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provice', to='accounts.province'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='province',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
